DROP TABLE IF EXISTS quizzes
CASCADE;

CREATE TABLE quizzes
(
  id SERIAL PRIMARY KEY NOT NULL,
  creator_id INTEGER REFERENCES users(id),
  name VARCHARR(25) NOT NULL,
  is_public BOOLEAN NOT NULL DEFAULT true,
);
