DROP TABLE IF EXISTS questions
CASCADE;
DROP TABLE IF EXISTS answers
CASCADE;

CREATE TABLE questions
(
  id SERIAL PRIMARY KEY NOT NULL,
  quiz_id INTEGER REFERENCES quizzes(id) ON DELETE CASCADE,
  text VARCHAR(255) NOT NULL
);


CREATE TABLE answers
(
  id SERIAL PRIMARY KEY NOT NULL,
  question_id INTEGER REFERENCES questions(id) ON DELETE CASCADE,
  choice VARCHAR(255) NOT NULL,
  is_correct BOOLEAN NOT NULL DEFAULT false
);
